# Generated by Django 4.2.27 on 2026-01-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortenerApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Optional expiration date and time", null=True
            ),
        ),
    ]
